import type { Metadata } from "next";
import { Lora, Poppins } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const lora = Lora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-Lora",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: "300",
  display: "swap",
  variable: "--font-Poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lora.variable} ${poppins.variable} font-Poppins`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
